### ISSUE TITLE
Credentials Login with LDAP

### ISSUE THREAD

**Issue by johannesheucher-gip** [Xyna-Factory/xyna-factory#181]
It shall be possible to make a credentials login (username, password) with Xyna and authenticate against an LDAP.

**Comment by csc-gip** [comment]
Using the LDAP as credential store (user password hash stored in LDAP) or authentication against the LDAP server itself (ldap-bind)?

**Comment by johannesheucher-gip** [comment]
It's planned as an authentication against the LDAP server itself (ldap-bind).
