### ISSUE TITLE
Support for RLIKE in Queries

### ISSUE THREAD

**Issue by LukasFey-GIP** [Xyna-Factory/xyna-factory#277]
Introduce a new function in query experssions that performs RLIKE - matching a String (Storable member variable) against a pattern (passed as argument).

**Comment by MichaelCHaas** [comment]
Syntax is different in Oracle and MySQL/MariaDB:
https://www.informatik-aktuell.de/betrieb/datenbanken/oracle-regular-expressions.html
https://mariadb.com/kb/en/regexp/
