### ISSUE TITLE
SSLKeystoreParameter Members not mappable in Workflow

### ISSUE THREAD

**Issue by corneliuslippert-gip** [Xyna-Factory/xyna-factory#33]
Copy&Paste-Error in https://github.com/GIP-SmartMercial/xyna-factory/blob/main/server/src/com/gip/xyna/xfmg/xopctrl/usermanagement/ldap/SSLKeystoreParameter.java#L420

Should be SSLKeystoreParameter.class instead of SSLParameter.class.

Leads to being not able to use the member variables in mappings.

**Comment by LukasFey-GIP** [comment]
Xyna Property (Factory Manager > Xyna Properties) "xprc.xfractwfe.different.typeresistant" must be true (default value)

**Comment by LukasFey-GIP** [comment]
A workflow containing a mapping that assings SSLKeystoreParameter-members can be saved and deployed, but throws an exception at runtime: "Parameter with name - does not exist"
