### ISSUE TITLE
Data protection - Implement De/Encoding of Url parameters

### ISSUE THREAD

**Issue by JeromeReyes-GIP** [Xyna-Factory/xyna-factory#385]
Motivation: 
With the GET method, parameters are passed in the URL and then typically logged by web servers and clients. If the web application contains links to other web applications, there is also the possibility that URL parameters are transmitted to these other web applications via the HTTP header "Referer" and appear there in the log files. This part of the problem could also be addressed (for most browsers) by using the HTTP response header "Referrer-Policy" (e.g. with the value "no-referrer"). In addition, it cannot be ruled out that a user uses a URL including protection The POST method, for example, copies parameters in the request body and passes them on.

Requirement:
URLs should be en/decoded by the server. One possible way would be to:

- Create a Xyna endpoint that is called by the GUI to en/decode the URL parameters.

**Comment by johannesheucher-gip** [comment]
[Manual](https://github.com/Xyna-Factory/xyna-zeta/wiki/Encryption)
