### ISSUE TITLE
Data protection - Include CSRF Token  in Request-/Response header

### ISSUE THREAD

**Issue by JeromeReyes-GIP** [Xyna-Factory/xyna-factory#386]
## Motivation
To prevent an evil website from session riding (when the cookie's same-site property is not set), each request needs to have a (session-unique) CSRF token to be sent with it inside the HTTP header.

## Requirements
- send session-unique token with the login response (as `sessionToken`)
  - use the token from the token cookie
- stop setting the token cookie
- validate the token for each HTTP request and reject it on mismatch
  - header attribute name: `Xyna-CSRF-Token`
  - for all HTTP methods (including `GET`)
  - not set for all kinds of login requests

## See also
Respective frontend issue: https://github.com/Xyna-Factory/xyna-zeta/issues/49

**Comment by LukasFey-GIP** [comment]
Breaking Change management:
* wiki: https://github.com/Xyna-Factory/xyna-factory/wiki/Breaking-Change:-CSRF%E2%80%90Token
* activation: https://github.com/Xyna-Factory/xyna-factory/issues/866
* cleanup: https://github.com/Xyna-Factory/xyna-factory/issues/867
