### ISSUE TITLE
Delete obsolete readmes

### ISSUE THREAD

**Issue by johannesheucher-gip** [Xyna-Factory/xyna-factory#428]
There is at least one obsolete readme file:
`https://github.com/Xyna-Factory/xyna-factory/blob/main/blackedition/readme.txt`

Search for more and delete/update them.

**Comment by Julian-Mueller-GIP** [comment]
> https://github.com/Xyna-Factory/xyna-factory/blob/main/blackedition/readme.txt

This file was updated recently.
