### ISSUE TITLE
Base64 enconding contains \r

### ISSUE THREAD

**Issue by csc-gip** [Xyna-Factory/xyna-factory#499]
https://github.com/Xyna-Factory/xyna-factory/blob/f571b360986d221a2ea2d1f85453ea685a71ddcc/server/src/com/gip/xyna/utils/misc/Base64.java#L38-L43

Removing only ```\n``` is not enough as the result also contains ```\r``` c.f. https://docs.oracle.com/en/java/javase/11/docs/api/java.base/java/util/Base64.html

This leads to https://github.com/Xyna-Factory/xyna-images/blob/ec029762cdebca787c0aecb27d8574ce44fbf30f/xynabase/k8s/xyna/pooldefinition.sh#L140C29-L140C140 still containing ```\r``` which breaks the generated XML.

The same seems to be happening here.
https://github.com/Xyna-Factory/xyna-images/blob/ec029762cdebca787c0aecb27d8574ce44fbf30f/xynabase/k8s/xyna/queue.sh#L148

Reproduce:
```bash
echo "securestorage.seed=com.gip.xyna" > /tmp/seed.properties

UUID=$(uuidgen)

XYNA_PATH="/opt/xyna/xyna_001"
# get classpath value with server libs
SERVERLIBS=""
SERVERLIBDIR="${XYNA_PATH}/server/lib/*.jar"
for SERVERLIBFILEPATH in $SERVERLIBDIR; do
	SERVERLIBS+=$SERVERLIBFILEPATH":"
done

java -Dxnwh.securestorage.seedfile=/tmp/seed.properties -classpath $SERVERLIBS \
       com.gip.xyna.xmcp.xfcli.scriptentry.EncryptPoolDefinitionPassword "secret_password" $UUID \
     | hexdump -C \
     | grep 0d
```

**Comment by csc-gip** [comment]
Breaking change as this did not happen with Xyna 8

**Comment by osuender** [comment]
Adopting the Fix from Xyna 8
