### ISSUE TITLE
Changing implentation type of instance services does not keep dokumentation.

### ISSUE THREAD

**Issue by TorbenSiegismund-GIP** [Xyna-Factory/xyna-factory#510]
Changing implementation type in instance service deletes dokumentation of service.

**Comment by LukasFey-GIP** [comment]
https://github.com/Xyna-Factory/xyna-factory/blob/main/modules/xmcp/guihttp/filterimpl/H5XdevFilter/src/com/gip/xyna/xact/filter/session/modify/operations/ChangeOperation.java
around line 611

Label, name and signature are copied from the old operation to the new. Documentation is missing.
