### ISSUE TITLE
Update SNMP service to allow newer algorithms

### ISSUE THREAD

**Issue by csc-gip** [Xyna-Factory/xyna-factory#585]
We use MD5 and DES as fixed algorithms when connecting with SNMPv3.
https://github.com/Xyna-Factory/xyna-factory/blob/1e55931f23af8fc5669e51af8ee9fd6c9bd10451/modules/xact/snmp/mdmimpl/SNMPService/src/xact/snmp/commands/impl/SNMPServiceServiceOperationImpl.java#L250-L255

SNMP4J supports newer secure algorithms like SHA-2 and AES. https://agentpp.com/api/java/snmp4j.html

We should update the service to allow for the selection of the algorithms.

Add optional attributes to Xyna datatype xact.snmp.SNMPConnectionDataV3 to allow for the selection of the auth and enc algorithms. Use Xyna properties to set the default algorithms to SHA-256 and AES-128.

AFAIK the trigger already supports newer algorithms by using the SNMP4J defaults.
https://github.com/Xyna-Factory/xyna-factory/blob/0bb312222e32960eae66d4b8d6743bd31c796cec/modules/xact/snmp/triggerimpl/SNMPTrigger/src/com/gip/xyna/xact/trigger/SNMPTrigger.java#L134

https://agentpp.com/doc/snmp4j/org.snmp4j/org/snmp4j/security/SecurityProtocols.html#addDefaultProtocols()

**Comment by LukasFey-GIP** [comment]
Breaking Change management:
* wiki: https://github.com/Xyna-Factory/xyna-factory/wiki/Breaking-Change:-New-SNMP-Algorithm-Defaults
* activation: https://github.com/Xyna-Factory/xyna-factory/issues/674
* cleanup: No cleanup required
