### ISSUE TITLE
Query soll den Glob ? unterstützen

### ISSUE THREAD

**Issue by MartinaFedakova** [Xyna-Factory/xyna-factory#646]
Zusätzlich zu dem Glob * in den Queries, der auf beliebig viele Zeichen passt, soll der Glob ? für ein beliebiges einzelnes Zeichen unterstützt werden.

**Comment by LukasFey-GIP** [comment]
Breaking Change management:
* wiki: https://github.com/Xyna-Factory/xyna-factory/wiki/Breaking-Change:-Single-Character-Wildcard-Support
* activation: #674 
* cleanup #675
