### ISSUE TITLE
Differences in States between `listapplicationdetails` and `listapplications` for "WARNING" and "ERROR"

### ISSUE THREAD

**Issue by LLdaniel** [Xyna-Factory/xyna-factory#759]
Xyna Factory Version: 9.0.4.1

*Problem:*
For a short summary of all the applications usually `./xynafactory.sh listapplictions -t` is used. For more details there is `./xynafactory.sh listapplicationdetails`.
If a specific app is in "ERROR" or "WARNING" state this state is only displayed when using `applicationdetails`, but not in `listapplciations`.

It seems that the state "STOPPED" or "RUNNING" always wins over "ERROR" and "WARNING".
I would like to suggest that for `listapplications` the behaviour should be opposite:
"ERROR" and "WARNING" should win over "STOPPED" or "RUNNING".

*Use case*
For a short health check in one glance it would be nice that `listapplications` directly displays erroneous apps or apps with warnings.

*How to reproduce*
Take an application with warning or error and try both commands. The result will differ:
```bash
./xynafactory.sh listapplications -applicationName 'Regression Support' -t
ApplicationName    │ VersionName               │ Workspace              │ Status      │ Objects │ Revision
═══════════════════╪═══════════════════════════╪════════════════════════╪═════════════╪═════════╪═════════
Regression Support │ 1.0                       │ -                      │ STOPPED     │ 1       │ 6766
```
vs. 
```bash
./xynafactory.sh listapplicationdetails -applicationName 'Regression Support' -versionName 1.0

 state WARNING
 requires Application 'Base', Version '1.0.19'
```

**Comment by corneliuslippert-gip** [comment]
In the past we removed the output from WARNING/ERROR from the default output of listapplications, because it may be expensive to calculate. You can still force the calculation with the "-v" Flag. It explicitly states in the help:

   -v,--verbose                    Calculate detailed error status

**Comment by LLdaniel** [comment]
Oh, I didn`t saw that. Only knew that the WARNING and ERROR states were part of the output. Thanks for the clarification. Obviously I overlooked the new `-v` option. 
Therefore I will close this issue.
